### ISSUE TITLE
Earth rotation rate shouldn't be locked to moon orbit

### ISSUE THREAD

**Issue by alwinv** [Microsoft/GalaxyExplorer#37]
The way it's currently animated, the Earth rotates 1 time for each Moon orbit - which makes the same side of the Earth always point to the Moon.

If you slow down the Moon's rotation rate to 1/2 and increase the Earth's rotation 2x, it wouldn't be as obvious that it's wrong.

The Earth actually rotates about 27 times on its axis for each complete Moon orbit around the earth. You don't need to do the full 27:1 ratio though, since this is not intending to be an astronomical model, but would be nice to have earth's rotation not be locked to the moon's orbit at least.

**Comment by ThitherCrane** [comment]
I would say that the animation is made for illustration purposes only and would not realistically describe motions of objects. For example, the Solar System View describes only earth’s movement around the sun but would not describe the moon ‘s movement in that frame of reference. A further complication is the fact that planets’ orbits around the sun are helical rather than circular. My conclusion is that the more the scripts try to depict reality, the more complex the code becomes.

**Comment by ChimeraScorn** [comment]
Alwin, is this a change you’d be interested in making?

-C

**Comment by timGerken** [comment]
Closed by #38
