### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ThitherCrane** [Microsoft/GalaxyExplorer#6]
1) Why was the app developed using Unity rather than Visual Studio? 

2) Can the app run from within Visual Studio?

3) Will development of HoloLens apps in the future always be done via Unity?

4) Does Unity allow stepping into scripts? 

5) What is the best / easiest way to debug the scripts?

6) Since the objective of the app is teaching programming, will the team publish YouTube videos showing how the app was developed and how the code works?

**Comment by danglingneuron** [comment]
1) There are two types of apps that will work on HoloLens. 

a) 2D apps which are regular/tweaked Windows 10 UWP apps - usually developed in C++.Net, C#.Net, VB.Net and XAML - using Visual Studio in most cases

b) 3D Holographic apps - which can be built via (i) Full game engine with editor e.g. Unity3D (ii) barebones DirectX (iii) in future - other engines and middleware

Please note that after doing work in Unity3D you will still have to export the project and then build / test / deploy it using Visual studio.

2) Yes the app will run from Visual Studio - thats the only way you can run/debug apps on HoloLens

3) No, other middle ware , engines will also get support e.g. Unreal Engine

4) Yes, Unity scripting is usually in C#.net as well. You can step through this code using Visual Studio debugging bridge while in UnityEditor and even after you export the project to Visual Studio.

5) Visual Studio

6) I think this would be helpful for beginners - the team can respond.

BUT I would rather recommend the team to make a list of BEST PRACTICES, lessons learnt, general guidelines, UX guidelines etc.  Since there is no "specific" practical guidance for Holographic apps at this time, i think this would be really valuable.

**Comment by ThitherCrane** [comment]
Thank you for the explanation. I can make simple rotating objects as shown below. However, I am interested in complex interactions, e.g., Internet searching with Bing, complex movements such the helical model and extraction of the core (I cannot see this in my PC app). Is Unity capable of supporting all these specifications?
![planet](https://cloud.githubusercontent.com/assets/18190665/14292231/2fed22c6-fb35-11e5-9e0a-39a1f9ef61f2.JPG)

**Comment by ChimeraScorn** [comment]
At this point, this is a conversation that is better suited to the forums over at https://forums.hololens.com or where we will do general dev support, or http://forum.unity3d.com/ where the Unity team does general dev support :)
